web:
  build: .
  environment:
    - PORT=80
    - MONGODB_URI=mongodb://mongo/clubble
  volumes:
    - ~/opt/clubble/uploads:/app/uploads
  links:
    - mongo
  ports:
    - "80:80"

mongo:
  image: mongo
